version: '3.1'

services:
  barber-shop-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - './logs/dev:/home/docker/app/logs'
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    environment:
      - APP_PORT=8080
      - MONGO_DB_HOST=mongodb
      - LOG_LEVEL=DEBUG
    #    secrets:
    #      - MONGO_DB_USERNAME
    #      - MONGO_DB_PASSWORD
    env_file:
      - .env
  mongodb:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=barber
    volumes:
      - ./docker/barber/init-scripts/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
#secrets:
#  MONGO_DB_USERNAME:
#    external: true
#  MONGO_DB_PASSWORD:
#    external: true
